language: python
cache:
  pip: true
python:
    - "3.6"
install:
    - pip install -r prerequirements.txt
    - pip install -r requirements.txt
env:
    - TOXENV=py36
script:
- tox
cache:
    directories:
        - $HOME/.cache/pre-commit
        - $HOME/.cache/pip
        - $HOME/.git/hooks/pre-commit
