language: python
cache:
  pip: false
python:
    - "3.6"
env:
    - TOXENV=py36
script:
- tox
cache:
    directories:
        - $HOME/.cache/pre-commit
        - $HOME/.cache/pip
        - $HOME/.git/hooks/pre-commit
